import random

low = 1
high = 100
ans=random.randint(low,high)
guess=0
is_running=True

while is_running:
    guess=int(input("Enter a guess between 1 and 100\n"))
    if guess >= ans :
        print(f"{ans} generated by computer")
        print("Guess is high")
    elif guess <= ans:
        print(f"{ans} generated by computer")
        print("Guess is low")
    else:
        is_running=False
        print("Correct")    
    
